version: "3.2"
services:
  flask:
    build: .
    restart: always
    ports:
      - "80:8080"
    environment:
      - DEPLOYMENT=development
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - .:/home/myuser