name: Test, Build, and Push Image to Docker

on:
  push:
    branches:
      - 'production'
      - 'development'
    tags:
      - 'v*'

jobs:
  runtest:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
      - id: setup_python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - id: install_dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - id: pytest
      - name: Test with pytest
        run: pytest -vv
      - name: Checkout code
        if: steps.pytest.outcome == 'success'
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: kaw393939/webizly
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: 'linux/arm64/v8, linux/amd64'
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}